# Generated by Django 4.2.10 on 2024-03-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ring2',
            fields=[
                ('nr', models.AutoField(primary_key=True, serialize=False)),
                ('based_on_ring1', models.PositiveIntegerField(default=0)),
                ('loc1', models.PositiveIntegerField(default=0)),
                ('loc2', models.PositiveIntegerField(default=0)),
                ('loc3', models.PositiveIntegerField(default=0)),
                ('loc4', models.PositiveIntegerField(default=0)),
                ('loc5', models.PositiveIntegerField(default=0)),
                ('loc6', models.PositiveIntegerField(default=0)),
                ('loc7', models.PositiveIntegerField(default=0)),
                ('loc8', models.PositiveIntegerField(default=0)),
                ('loc9', models.PositiveIntegerField(default=0)),
                ('loc10', models.PositiveIntegerField(default=0)),
                ('loc11', models.PositiveIntegerField(default=0)),
                ('loc12', models.PositiveIntegerField(default=0)),
                ('loc13', models.PositiveIntegerField(default=0)),
                ('loc14', models.PositiveIntegerField(default=0)),
                ('loc15', models.PositiveIntegerField(default=0)),
                ('loc16', models.PositiveIntegerField(default=0)),
                ('loc17', models.PositiveIntegerField(default=0)),
                ('loc18', models.PositiveIntegerField(default=0)),
                ('loc23', models.PositiveIntegerField(default=0)),
                ('loc24', models.PositiveIntegerField(default=0)),
                ('loc25', models.PositiveIntegerField(default=0)),
                ('loc26', models.PositiveIntegerField(default=0)),
                ('loc31', models.PositiveIntegerField(default=0)),
                ('loc32', models.PositiveIntegerField(default=0)),
                ('loc33', models.PositiveIntegerField(default=0)),
                ('loc34', models.PositiveIntegerField(default=0)),
                ('loc39', models.PositiveIntegerField(default=0)),
                ('loc40', models.PositiveIntegerField(default=0)),
                ('loc41', models.PositiveIntegerField(default=0)),
                ('loc42', models.PositiveIntegerField(default=0)),
                ('loc47', models.PositiveIntegerField(default=0)),
                ('loc48', models.PositiveIntegerField(default=0)),
                ('loc49', models.PositiveIntegerField(default=0)),
                ('loc50', models.PositiveIntegerField(default=0)),
                ('loc51', models.PositiveIntegerField(default=0)),
                ('loc52', models.PositiveIntegerField(default=0)),
                ('loc53', models.PositiveIntegerField(default=0)),
                ('loc54', models.PositiveIntegerField(default=0)),
                ('loc55', models.PositiveIntegerField(default=0)),
                ('loc56', models.PositiveIntegerField(default=0)),
                ('loc57', models.PositiveIntegerField(default=0)),
                ('loc58', models.PositiveIntegerField(default=0)),
                ('loc59', models.PositiveIntegerField(default=0)),
                ('loc60', models.PositiveIntegerField(default=0)),
                ('loc61', models.PositiveIntegerField(default=0)),
                ('loc62', models.PositiveIntegerField(default=0)),
                ('loc63', models.PositiveIntegerField(default=0)),
                ('loc64', models.PositiveIntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ring2',
            },
        ),
    ]
