# Generated by Django 4.2.7 on 2023-11-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece8x2',
            fields=[
                ('nr', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('side2', models.CharField(max_length=2)),
                ('side4', models.CharField(max_length=2)),
                ('nr1', models.PositiveSmallIntegerField()),
                ('nr2', models.PositiveSmallIntegerField()),
                ('nr3', models.PositiveSmallIntegerField()),
                ('nr4', models.PositiveSmallIntegerField()),
                ('nr5', models.PositiveSmallIntegerField()),
                ('nr6', models.PositiveSmallIntegerField()),
                ('nr7', models.PositiveSmallIntegerField()),
                ('nr8', models.PositiveSmallIntegerField()),
                ('nr9', models.PositiveSmallIntegerField()),
                ('nr10', models.PositiveSmallIntegerField()),
                ('nr11', models.PositiveSmallIntegerField()),
                ('nr12', models.PositiveSmallIntegerField()),
                ('nr13', models.PositiveSmallIntegerField()),
                ('nr14', models.PositiveSmallIntegerField()),
                ('nr15', models.PositiveSmallIntegerField()),
                ('nr16', models.PositiveSmallIntegerField()),
                ('rot1', models.PositiveSmallIntegerField()),
                ('rot2', models.PositiveSmallIntegerField()),
                ('rot3', models.PositiveSmallIntegerField()),
                ('rot4', models.PositiveSmallIntegerField()),
                ('rot5', models.PositiveSmallIntegerField()),
                ('rot6', models.PositiveSmallIntegerField()),
                ('rot7', models.PositiveSmallIntegerField()),
                ('rot8', models.PositiveSmallIntegerField()),
                ('rot9', models.PositiveSmallIntegerField()),
                ('rot10', models.PositiveSmallIntegerField()),
                ('rot11', models.PositiveSmallIntegerField()),
                ('rot12', models.PositiveSmallIntegerField()),
                ('rot13', models.PositiveSmallIntegerField()),
                ('rot14', models.PositiveSmallIntegerField()),
                ('rot15', models.PositiveSmallIntegerField()),
                ('rot16', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Piece 8x2',
                'verbose_name_plural': 'Pieces 8x2',
            },
        ),
    ]

# end of file
