# Generated by Django 4.2.7 on 2024-01-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkQueue', '0002_alter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='when_done',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
