# Generated by Django 4.2.7 on 2024-01-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkQueue', '0003_alter_work_when_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='job_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
