# Generated by Django 4.2.7 on 2024-01-29 07:44

from django.db import migrations, models


def set_created_from(apps, _):
    used_klas = apps.get_model('WorkQueue', 'ProcessorUsedPieces')

    for used in used_klas.objects.all():
        if used.processor > 0:
            used.created_from = used.processor - 1
            used.save(update_fields=['created_from'])
    # for


class Migration(migrations.Migration):

    dependencies = [
        ('WorkQueue', '0008_reached_dead_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorusedpieces',
            name='created_from',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(set_created_from, reverse_code=migrations.RunPython.noop)
    ]

# end of file
