# Generated by Django 4.2.7 on 2024-01-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkQueue', '0010_used_loc_p2x2nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorusedpieces',
            name='choices',
            field=models.TextField(blank=True, default=''),
        ),
    ]
