# Generated by Django 4.2.7 on 2024-02-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkQueue', '0012_work_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='seed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
