# Generated by Django 4.2.10 on 2024-03-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkQueue', '0014_work_start_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorusedpieces',
            name='from_ring1',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
