# Generated by Django 4.2.11 on 2024-04-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block2x1',
            fields=[
                ('nr', models.AutoField(primary_key=True, serialize=False)),
                ('block1_nr', models.PositiveIntegerField()),
                ('rot1', models.PositiveSmallIntegerField(default=0)),
                ('block2_nr', models.PositiveIntegerField()),
                ('rot2', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Block2x1',
            },
        ),
    ]
