# Generated by Django 4.2.7 on 2023-11-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ring4',
            fields=[
                ('nr', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('c1', models.PositiveIntegerField()),
                ('c2', models.PositiveIntegerField()),
                ('c3', models.PositiveIntegerField()),
                ('c4', models.PositiveIntegerField()),
                ('b1', models.PositiveIntegerField()),
                ('b2', models.PositiveIntegerField()),
                ('b3', models.PositiveIntegerField()),
                ('b4', models.PositiveIntegerField()),
                ('b5', models.PositiveIntegerField()),
                ('b6', models.PositiveIntegerField()),
                ('b7', models.PositiveIntegerField()),
                ('b8', models.PositiveIntegerField()),
                ('p1', models.PositiveIntegerField()),
                ('p2', models.PositiveIntegerField()),
                ('p3', models.PositiveIntegerField()),
                ('p4', models.PositiveIntegerField()),
                ('p5', models.PositiveIntegerField()),
                ('p6', models.PositiveIntegerField()),
                ('p7', models.PositiveIntegerField()),
                ('p8', models.PositiveIntegerField()),
                ('p9', models.PositiveIntegerField()),
                ('p10', models.PositiveIntegerField()),
                ('p11', models.PositiveIntegerField()),
                ('p12', models.PositiveIntegerField()),
                ('p13', models.PositiveIntegerField()),
                ('p14', models.PositiveIntegerField()),
                ('p15', models.PositiveIntegerField()),
                ('p16', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Ring4',
            },
        ),
    ]

# end of file
