# Generated by Django 4.2.7 on 2023-12-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ring1',
            fields=[
                ('nr', models.AutoField(primary_key=True, serialize=False)),
                ('processor', models.PositiveIntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('nr1', models.PositiveIntegerField()),
                ('nr2', models.PositiveIntegerField()),
                ('nr3', models.PositiveIntegerField()),
                ('nr4', models.PositiveIntegerField()),
                ('nr5', models.PositiveIntegerField()),
                ('nr6', models.PositiveIntegerField()),
                ('nr7', models.PositiveIntegerField()),
                ('nr8', models.PositiveIntegerField()),
                ('nr9', models.PositiveIntegerField()),
                ('nr16', models.PositiveIntegerField()),
                ('nr17', models.PositiveIntegerField()),
                ('nr24', models.PositiveIntegerField()),
                ('nr25', models.PositiveIntegerField()),
                ('nr32', models.PositiveIntegerField()),
                ('nr33', models.PositiveIntegerField()),
                ('nr40', models.PositiveIntegerField()),
                ('nr41', models.PositiveIntegerField()),
                ('nr48', models.PositiveIntegerField()),
                ('nr49', models.PositiveIntegerField()),
                ('nr56', models.PositiveIntegerField()),
                ('nr57', models.PositiveIntegerField()),
                ('nr58', models.PositiveIntegerField()),
                ('nr59', models.PositiveIntegerField()),
                ('nr60', models.PositiveIntegerField()),
                ('nr61', models.PositiveIntegerField()),
                ('nr62', models.PositiveIntegerField()),
                ('nr63', models.PositiveIntegerField()),
                ('nr64', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Ring1',
            },
        ),
    ]
