# Generated by Django 4.2.7 on 2024-01-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ring1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ring1',
            name='nr10',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ring1',
            name='nr11',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ring1',
            name='nr14',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ring1',
            name='nr15',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ring1',
            name='nr18',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ring1',
            name='nr23',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ring1',
            name='nr36',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ring1',
            name='nr42',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ring1',
            name='nr47',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ring1',
            name='nr50',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ring1',
            name='nr51',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ring1',
            name='nr54',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ring1',
            name='nr55',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
