# Generated by Django 4.2.7 on 2024-02-12 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ring1', '0005_corner34_corner12'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corner34',
            old_name='side3_left',
            new_name='side1_left',
        ),
        migrations.RenameField(
            model_name='corner34',
            old_name='side3_right',
            new_name='side1_right',
        ),
    ]
