# Generated by Django 4.2.7 on 2024-02-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ring1', '0006_renames'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corner12',
            options={'verbose_name': 'Corner12'},
        ),
        migrations.AlterModelOptions(
            name='corner34',
            options={'verbose_name': 'Corner34'},
        ),
    ]
