# Generated by Django 4.2.7 on 2024-02-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ring1', '0007_alter_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ring1',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='ring1',
            name='processor',
        ),
        migrations.AddField(
            model_name='corner1',
            name='seed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corner12',
            name='seed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corner2',
            name='seed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corner3',
            name='seed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corner34',
            name='seed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corner4',
            name='seed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ring1',
            name='seed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='corner1',
            index=models.Index(fields=['seed'], name='Ring1_corne_seed_384e78_idx'),
        ),
        migrations.AddIndex(
            model_name='corner12',
            index=models.Index(fields=['seed'], name='Ring1_corne_seed_4ee89b_idx'),
        ),
        migrations.AddIndex(
            model_name='corner2',
            index=models.Index(fields=['seed'], name='Ring1_corne_seed_15bbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='corner3',
            index=models.Index(fields=['seed'], name='Ring1_corne_seed_5b2732_idx'),
        ),
        migrations.AddIndex(
            model_name='corner34',
            index=models.Index(fields=['seed'], name='Ring1_corne_seed_a49435_idx'),
        ),
        migrations.AddIndex(
            model_name='corner4',
            index=models.Index(fields=['seed'], name='Ring1_corne_seed_7c6e90_idx'),
        ),
    ]
