# Generated by Django 4.2.10 on 2024-03-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ring1', '0008_seed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Corner1',
        ),
        migrations.DeleteModel(
            name='Corner12',
        ),
        migrations.DeleteModel(
            name='Corner2',
        ),
        migrations.DeleteModel(
            name='Corner3',
        ),
        migrations.DeleteModel(
            name='Corner34',
        ),
        migrations.DeleteModel(
            name='Corner4',
        ),
        migrations.RemoveField(
            model_name='ring1',
            name='nr36',
        ),
        migrations.AddField(
            model_name='ring1',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
