# Generated by Django 4.2.11 on 2024-04-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ring3',
            fields=[
                ('nr', models.AutoField(primary_key=True, serialize=False)),
                ('loc19', models.PositiveIntegerField(default=0)),
                ('loc20', models.PositiveIntegerField(default=0)),
                ('loc21', models.PositiveIntegerField(default=0)),
                ('loc22', models.PositiveIntegerField(default=0)),
                ('loc27', models.PositiveIntegerField(default=0)),
                ('loc30', models.PositiveIntegerField(default=0)),
                ('loc35', models.PositiveIntegerField(default=0)),
                ('loc38', models.PositiveIntegerField(default=0)),
                ('loc43', models.PositiveIntegerField(default=0)),
                ('loc44', models.PositiveIntegerField(default=0)),
                ('loc45', models.PositiveIntegerField(default=0)),
                ('loc46', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ring3',
            },
        ),
    ]
