# Generated by Django 4.2.7 on 2023-11-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corner4',
            fields=[
                ('nr', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('c1', models.PositiveIntegerField()),
                ('c2', models.PositiveIntegerField()),
                ('c3', models.PositiveIntegerField()),
                ('c4', models.PositiveIntegerField()),
                ('b1', models.PositiveIntegerField()),
                ('b2', models.PositiveIntegerField()),
                ('p1', models.PositiveIntegerField()),
                ('p2', models.PositiveIntegerField()),
                ('p3', models.PositiveIntegerField()),
                ('p4', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Corner4',
            },
        ),
    ]

# end of file
