# Generated by Django 4.2.7 on 2023-11-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Corners4', '0002_corner4_side2_corner4_side3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corner4',
            old_name='c1',
            new_name='c',
        ),
        migrations.RemoveField(
            model_name='corner4',
            name='c2',
        ),
        migrations.RemoveField(
            model_name='corner4',
            name='c3',
        ),
        migrations.RemoveField(
            model_name='corner4',
            name='c4',
        ),
    ]
