# Generated by Django 4.2.7 on 2023-11-11 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Corners4', '0003_rename_c1_corner4_c_remove_corner4_c2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corner4',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='corner4',
            name='p4',
        ),
        migrations.RemoveField(
            model_name='corner4',
            name='side2',
        ),
        migrations.RemoveField(
            model_name='corner4',
            name='side3',
        ),
    ]
