# Generated by Django 4.2.6 on 2023-10-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FourSides',
            fields=[
                ('nr', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('four_sides', models.CharField(default='XXXX', max_length=4)),
            ],
            options={'verbose_name': 'Four sides', 'verbose_name_plural': 'Four sides'},
        ),
        migrations.CreateModel(
            name='Piece4x4',
            fields=[
                ('nr', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nr1', models.PositiveSmallIntegerField()),
                ('nr2', models.PositiveSmallIntegerField()),
                ('nr3', models.PositiveSmallIntegerField()),
                ('nr4', models.PositiveSmallIntegerField()),
                ('nr5', models.PositiveSmallIntegerField()),
                ('nr6', models.PositiveSmallIntegerField()),
                ('nr7', models.PositiveSmallIntegerField()),
                ('nr8', models.PositiveSmallIntegerField()),
                ('nr9', models.PositiveSmallIntegerField()),
                ('nr10', models.PositiveSmallIntegerField()),
                ('nr11', models.PositiveSmallIntegerField()),
                ('nr12', models.PositiveSmallIntegerField()),
                ('nr13', models.PositiveSmallIntegerField()),
                ('nr14', models.PositiveSmallIntegerField()),
                ('nr15', models.PositiveSmallIntegerField()),
                ('nr16', models.PositiveSmallIntegerField()),
                ('rot1', models.PositiveSmallIntegerField()),
                ('rot2', models.PositiveSmallIntegerField()),
                ('rot3', models.PositiveSmallIntegerField()),
                ('rot4', models.PositiveSmallIntegerField()),
                ('rot5', models.PositiveSmallIntegerField()),
                ('rot6', models.PositiveSmallIntegerField()),
                ('rot7', models.PositiveSmallIntegerField()),
                ('rot8', models.PositiveSmallIntegerField()),
                ('rot9', models.PositiveSmallIntegerField()),
                ('rot10', models.PositiveSmallIntegerField()),
                ('rot11', models.PositiveSmallIntegerField()),
                ('rot12', models.PositiveSmallIntegerField()),
                ('rot13', models.PositiveSmallIntegerField()),
                ('rot14', models.PositiveSmallIntegerField()),
                ('rot15', models.PositiveSmallIntegerField()),
                ('rot16', models.PositiveSmallIntegerField()),
                ('side1', models.PositiveIntegerField()),
                ('side2', models.PositiveIntegerField()),
                ('side3', models.PositiveIntegerField()),
                ('side4', models.PositiveIntegerField()),
                ('piece2x2_nr1', models.PositiveIntegerField()),
            ],
            options={'verbose_name': 'Piece 4x4', 'verbose_name_plural': 'Pieces 4x4'},
        ),
    ]

# end of file
