# Generated by Django 4.2.6 on 2023-11-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pieces4x4', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='piece4x4',
            index=models.Index(fields=['nr1'], name='Pieces4x4_p_nr1_0bbeaf_idx')),
        migrations.AddIndex(
            model_name='piece4x4',
            index=models.Index(fields=['nr11'], name='Pieces4x4_p_nr11_d84a38_idx')),
    ]

# end of file
