# Generated by Django 4.2.7 on 2023-11-07 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pieces4x4', '0002_add_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FourSides',
        ),
        migrations.RemoveField(
            model_name='piece4x4',
            name='piece2x2_nr1',
        ),
        migrations.RemoveField(
            model_name='piece4x4',
            name='side1',
        ),
        migrations.RemoveField(
            model_name='piece4x4',
            name='side2',
        ),
        migrations.RemoveField(
            model_name='piece4x4',
            name='side3',
        ),
        migrations.RemoveField(
            model_name='piece4x4',
            name='side4',
        ),
    ]
