# Generated by Django 4.2.7 on 2023-11-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pieces4x4', '0003_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece4x4',
            name='side2',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='piece4x4',
            name='side3',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddIndex(
            model_name='piece4x4',
            index=models.Index(fields=['side2'], name='Pieces4x4_p_side2_1ec12c_idx'),
        ),
        migrations.AddIndex(
            model_name='piece4x4',
            index=models.Index(fields=['side3'], name='Pieces4x4_p_side3_4ab1a5_idx'),
        ),
    ]

# end of file
