# Generated by Django 4.2.7 on 2023-11-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pieces4x4', '0004_sides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece4x4',
            name='nr',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
