# Generated by Django 4.2.7 on 2023-11-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar12x2',
            fields=[
                ('nr', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('h1', models.PositiveSmallIntegerField()),
                ('h2', models.PositiveSmallIntegerField()),
                ('p1', models.PositiveIntegerField()),
                ('p2', models.PositiveIntegerField()),
                ('p3', models.PositiveIntegerField()),
                ('p4', models.PositiveIntegerField()),
                ('p5', models.PositiveIntegerField()),
                ('p6', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Bar12x2',
                'indexes': [models.Index(fields=['h1'], name='Bars12x2_ba_h1_ea490b_idx'), models.Index(fields=['h2'], name='Bars12x2_ba_h2_9189fb_idx'), models.Index(fields=['p1'], name='Bars12x2_ba_p1_669e02_idx'), models.Index(fields=['p6'], name='Bars12x2_ba_p6_1aa907_idx')],
            },
        ),
    ]
