# Generated by Django 4.2.7 on 2023-11-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pieces2x2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block2x8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField()),
                ('p1', models.PositiveIntegerField()),
                ('p2', models.PositiveIntegerField()),
                ('p3', models.PositiveIntegerField()),
                ('p4', models.PositiveIntegerField()),
                ('side1', models.PositiveIntegerField()),
                ('side2', models.PositiveIntegerField()),
                ('side3', models.PositiveIntegerField()),
                ('side4', models.PositiveIntegerField()),
                ('b1', models.PositiveIntegerField()),
                ('b2', models.PositiveIntegerField()),
                ('b3', models.PositiveIntegerField()),
                ('b4', models.PositiveIntegerField()),
                ('nr1', models.PositiveSmallIntegerField()),
                ('nr2', models.PositiveSmallIntegerField()),
                ('nr3', models.PositiveSmallIntegerField()),
                ('nr4', models.PositiveSmallIntegerField()),
                ('nr5', models.PositiveSmallIntegerField()),
                ('nr6', models.PositiveSmallIntegerField()),
                ('nr7', models.PositiveSmallIntegerField()),
                ('nr8', models.PositiveSmallIntegerField()),
                ('nr9', models.PositiveSmallIntegerField()),
                ('nr10', models.PositiveSmallIntegerField()),
                ('nr11', models.PositiveSmallIntegerField()),
                ('nr12', models.PositiveSmallIntegerField()),
                ('nr13', models.PositiveSmallIntegerField()),
                ('nr14', models.PositiveSmallIntegerField()),
                ('nr15', models.PositiveSmallIntegerField()),
                ('nr16', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Block 2x8',
                'verbose_name_plural': 'Blocks 2x8',
                'indexes': [models.Index(fields=['b1'], name='Pieces2x2_b_b1_095620_idx'), models.Index(fields=['b2'], name='Pieces2x2_b_b2_683b90_idx'), models.Index(fields=['b3'], name='Pieces2x2_b_b3_39ab93_idx'), models.Index(fields=['b4'], name='Pieces2x2_b_b4_b58d4d_idx'), models.Index(fields=['nr1'], name='Pieces2x2_b_nr1_d2d2c6_idx'), models.Index(fields=['nr2'], name='Pieces2x2_b_nr2_defde5_idx'), models.Index(fields=['nr3'], name='Pieces2x2_b_nr3_ea89f9_idx'), models.Index(fields=['nr4'], name='Pieces2x2_b_nr4_bdb4bf_idx'), models.Index(fields=['nr5'], name='Pieces2x2_b_nr5_1eabe9_idx'), models.Index(fields=['nr6'], name='Pieces2x2_b_nr6_ea45cb_idx'), models.Index(fields=['nr7'], name='Pieces2x2_b_nr7_e69088_idx'), models.Index(fields=['nr8'], name='Pieces2x2_b_nr8_7624bf_idx'), models.Index(fields=['nr9'], name='Pieces2x2_b_nr9_663161_idx'), models.Index(fields=['nr10'], name='Pieces2x2_b_nr10_045721_idx'), models.Index(fields=['nr11'], name='Pieces2x2_b_nr11_609afd_idx'), models.Index(fields=['nr12'], name='Pieces2x2_b_nr12_6dccf9_idx'), models.Index(fields=['nr13'], name='Pieces2x2_b_nr13_30f68d_idx'), models.Index(fields=['nr14'], name='Pieces2x2_b_nr14_fd06d6_idx'), models.Index(fields=['nr15'], name='Pieces2x2_b_nr15_38746d_idx'), models.Index(fields=['nr16'], name='Pieces2x2_b_nr16_7fe55e_idx')],
            },
        ),
    ]
