# Generated by Django 4.2.7 on 2023-12-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pieces2x2', '0003_block2x8_processor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TwoSides',
            new_name='TwoSide',
        ),
        migrations.CreateModel(
            name='TwoSideOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.PositiveSmallIntegerField()),
                ('two_side', models.PositiveSmallIntegerField()),
            ],
        ),
    ]

# end of file
