# Generated by Django 4.2.7 on 2023-12-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pieces2x2', '0006_evalprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalprogress',
            name='solve_order',
            field=models.CharField(max_length=250),
        ),
    ]
