# Generated by Django 4.2.7 on 2023-11-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solutions', '0002_half6'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quart6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.PositiveIntegerField(default=0)),
                ('based_on_4x4', models.PositiveBigIntegerField()),
                ('type', models.PositiveSmallIntegerField()),
                ('p1', models.PositiveIntegerField()),
                ('c1', models.PositiveIntegerField()),
                ('p2', models.PositiveIntegerField()),
                ('nr1', models.PositiveSmallIntegerField()),
                ('nr2', models.PositiveSmallIntegerField()),
                ('nr3', models.PositiveSmallIntegerField()),
                ('nr4', models.PositiveSmallIntegerField()),
                ('nr5', models.PositiveSmallIntegerField()),
                ('nr6', models.PositiveSmallIntegerField()),
                ('nr7', models.PositiveSmallIntegerField()),
                ('nr8', models.PositiveSmallIntegerField()),
                ('nr9', models.PositiveSmallIntegerField()),
                ('nr10', models.PositiveSmallIntegerField()),
                ('nr11', models.PositiveSmallIntegerField()),
                ('nr12', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Quart6',
                'verbose_name_plural': 'Quart6',
                'indexes': [models.Index(fields=['nr1'], name='Solutions_q_nr1_e104ae_idx'), models.Index(fields=['nr2'], name='Solutions_q_nr2_8b52a4_idx'), models.Index(fields=['nr3'], name='Solutions_q_nr3_97dc24_idx'), models.Index(fields=['nr4'], name='Solutions_q_nr4_dd6d75_idx'), models.Index(fields=['nr5'], name='Solutions_q_nr5_1bf579_idx'), models.Index(fields=['nr6'], name='Solutions_q_nr6_6fadfe_idx'), models.Index(fields=['nr7'], name='Solutions_q_nr7_2753a1_idx'), models.Index(fields=['nr8'], name='Solutions_q_nr8_99ad1f_idx'), models.Index(fields=['nr9'], name='Solutions_q_nr9_af40b4_idx'), models.Index(fields=['nr10'], name='Solutions_q_nr10_06c3ea_idx'), models.Index(fields=['nr11'], name='Solutions_q_nr11_754d3d_idx'), models.Index(fields=['nr12'], name='Solutions_q_nr12_91ed19_idx')],
            },
        ),
    ]
