# Generated by Django 4.2.7 on 2023-11-29 19:53

from django.db import migrations, models
from Partial4x4.models import NRS_PARTIAL_4X4


def push_to_partial4x4(apps, _):
    sol6x6_klas = apps.get_model('Solutions', 'Solution6x6')
    sol4x4_klas = apps.get_model('Solutions', 'Solution4x4')
    part4x4_klas = apps.get_model('Partial4x4', 'Partial4x4')

    nrs = list(sol6x6_klas
               .objects
               .exclude(nr50=0).exclude(nr55=0).exclude(nr10=0).exclude(nr15=0)
               .distinct('based_on_4x4')
               .values_list('based_on_4x4', flat=True))

    bulk = list()
    for sol in sol4x4_klas.objects.filter(pk__in=nrs):
        part = part4x4_klas(
                    pk=sol.pk,
                    when=sol.when,
                    processor=0,
                    is_processed=sol.is_processed)

        for nr in range(1, 64+1):
            if nr in NRS_PARTIAL_4X4:
                field = 'nr%s' % nr
            else:
                field = 'note%s' % nr

            setattr(part, field, getattr(sol, field))
        # for

        bulk.append(part)
    # for

    part4x4_klas.objects.bulk_create(bulk)
    print('migrated %s Partial4x4' % len(bulk))


class Migration(migrations.Migration):

    dependencies = [
        ('Solutions', '0003_quart6'),
        ('Partial4x4', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(push_to_partial4x4, reverse_code=migrations.RunPython.noop),
    ]

# end of file
