# Generated by Django 4.2.7 on 2023-11-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solutions', '0003_solution4x4_solution6x6'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution6x6',
            name='based_on_4x4',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
