# Generated by Django 4.2.7 on 2023-11-29 19:53

from django.db import migrations, models
from Partial6x6.models import NRS_PARTIAL_6X6


def push_to_partial6x6(apps, _):
    sol6x6_klas = apps.get_model('Solutions', 'Solution6x6')
    part6x6_klas = apps.get_model('Partial6x6', 'Partial6x6')

    bulk = list()
    for sol in sol6x6_klas.objects.exclude(nr10=0).exclude(nr15=0).exclude(nr50=0).exclude(nr55=0):
        part = part6x6_klas(
                    when=sol.when,
                    processor=0,
                    is_processed=sol.is_processed,
                    based_on_4x4=sol.based_on_4x4)

        for nr in range(1, 64+1):
            if nr in NRS_PARTIAL_6X6:
                field = 'nr%s' % nr
            else:
                field = 'note%s' % nr

            setattr(part, field, getattr(sol, field))
        # for

        bulk.append(part)
    # for

    part6x6_klas.objects.bulk_create(bulk)
    print('migrated %s Partial6x6' % len(bulk))


class Migration(migrations.Migration):

    dependencies = [
        ('Solutions', '0004_partial4x4'),
        ('Partial6x6', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(push_to_partial6x6, reverse_code=migrations.RunPython.noop),
    ]

# end of file
