# Generated by Django 4.2.7 on 2023-11-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solutions', '0004_solution6x6_based_on_4x4'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution4x4',
            name='processor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solution6x6',
            name='processor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
