# Generated by Django 4.2.7 on 2023-12-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solutions', '0004_partial6x6'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Half6',
        ),
        migrations.DeleteModel(
            name='Quart6',
        ),
        migrations.DeleteModel(
            name='Solution4x4',
        ),
        migrations.DeleteModel(
            name='Solution6x6',
        ),
    ]
