# Generated by Django 4.2.7 on 2023-12-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # geen dependencies
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Partial4x4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('processor', models.PositiveIntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('note1', models.CharField(blank=True, default='', max_length=30)),
                ('note2', models.CharField(blank=True, default='', max_length=30)),
                ('note3', models.CharField(blank=True, default='', max_length=30)),
                ('note4', models.CharField(blank=True, default='', max_length=30)),
                ('note5', models.CharField(blank=True, default='', max_length=30)),
                ('note6', models.CharField(blank=True, default='', max_length=30)),
                ('note7', models.CharField(blank=True, default='', max_length=30)),
                ('note8', models.CharField(blank=True, default='', max_length=30)),
                ('note9', models.CharField(blank=True, default='', max_length=30)),
                ('note10', models.CharField(blank=True, default='', max_length=30)),
                ('note11', models.CharField(blank=True, default='', max_length=30)),
                ('note12', models.CharField(blank=True, default='', max_length=30)),
                ('note13', models.CharField(blank=True, default='', max_length=30)),
                ('note14', models.CharField(blank=True, default='', max_length=30)),
                ('note15', models.CharField(blank=True, default='', max_length=30)),
                ('note16', models.CharField(blank=True, default='', max_length=30)),
                ('note17', models.CharField(blank=True, default='', max_length=30)),
                ('note18', models.CharField(blank=True, default='', max_length=30)),
                ('nr19', models.PositiveIntegerField()),
                ('nr20', models.PositiveIntegerField()),
                ('nr21', models.PositiveIntegerField()),
                ('nr22', models.PositiveIntegerField()),
                ('note23', models.CharField(blank=True, default='', max_length=30)),
                ('note24', models.CharField(blank=True, default='', max_length=30)),
                ('note25', models.CharField(blank=True, default='', max_length=30)),
                ('note26', models.CharField(blank=True, default='', max_length=30)),
                ('nr27', models.PositiveIntegerField()),
                ('nr28', models.PositiveIntegerField()),
                ('nr29', models.PositiveIntegerField()),
                ('nr30', models.PositiveIntegerField()),
                ('note31', models.CharField(blank=True, default='', max_length=30)),
                ('note32', models.CharField(blank=True, default='', max_length=30)),
                ('note33', models.CharField(blank=True, default='', max_length=30)),
                ('note34', models.CharField(blank=True, default='', max_length=30)),
                ('nr35', models.PositiveIntegerField()),
                ('nr36', models.PositiveIntegerField()),
                ('nr37', models.PositiveIntegerField()),
                ('nr38', models.PositiveIntegerField()),
                ('note39', models.CharField(blank=True, default='', max_length=30)),
                ('note40', models.CharField(blank=True, default='', max_length=30)),
                ('note41', models.CharField(blank=True, default='', max_length=30)),
                ('note42', models.CharField(blank=True, default='', max_length=30)),
                ('nr43', models.PositiveIntegerField()),
                ('nr44', models.PositiveIntegerField()),
                ('nr45', models.PositiveIntegerField()),
                ('nr46', models.PositiveIntegerField()),
                ('note47', models.CharField(blank=True, default='', max_length=30)),
                ('note48', models.CharField(blank=True, default='', max_length=30)),
                ('note49', models.CharField(blank=True, default='', max_length=30)),
                ('note50', models.CharField(blank=True, default='', max_length=30)),
                ('note51', models.CharField(blank=True, default='', max_length=30)),
                ('note52', models.CharField(blank=True, default='', max_length=30)),
                ('note53', models.CharField(blank=True, default='', max_length=30)),
                ('note54', models.CharField(blank=True, default='', max_length=30)),
                ('note55', models.CharField(blank=True, default='', max_length=30)),
                ('note56', models.CharField(blank=True, default='', max_length=30)),
                ('note57', models.CharField(blank=True, default='', max_length=30)),
                ('note58', models.CharField(blank=True, default='', max_length=30)),
                ('note59', models.CharField(blank=True, default='', max_length=30)),
                ('note60', models.CharField(blank=True, default='', max_length=30)),
                ('note61', models.CharField(blank=True, default='', max_length=30)),
                ('note62', models.CharField(blank=True, default='', max_length=30)),
                ('note63', models.CharField(blank=True, default='', max_length=30)),
                ('note64', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Partial 4x4',
                'verbose_name_plural': 'Partial 4x4s',
            },
        ),
    ]

# end of file
