# Generated by Django 4.2.7 on 2023-11-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Border4x2',
            fields=[
                ('nr', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('side2', models.CharField(max_length=2)),
                ('side4', models.CharField(max_length=2)),
                ('nr1', models.PositiveSmallIntegerField()),
                ('nr2', models.PositiveSmallIntegerField()),
                ('nr3', models.PositiveSmallIntegerField()),
                ('nr4', models.PositiveSmallIntegerField()),
                ('nr5', models.PositiveSmallIntegerField()),
                ('nr6', models.PositiveSmallIntegerField()),
                ('nr7', models.PositiveSmallIntegerField()),
                ('nr8', models.PositiveSmallIntegerField()),
                ('rot1', models.PositiveSmallIntegerField()),
                ('rot2', models.PositiveSmallIntegerField()),
                ('rot3', models.PositiveSmallIntegerField()),
                ('rot4', models.PositiveSmallIntegerField()),
                ('rot5', models.PositiveSmallIntegerField()),
                ('rot6', models.PositiveSmallIntegerField()),
                ('rot7', models.PositiveSmallIntegerField()),
                ('rot8', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Border 4x2',
                'verbose_name_plural': 'Borders 4x2',
            },
        ),
    ]
