# Generated by Django 4.2.7 on 2023-11-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Borders4x2', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='border4x2',
            index=models.Index(fields=['side2'], name='Borders4x2__side2_5883e1_idx'),
        ),
    ]
