# Generated by Django 4.2.7 on 2023-11-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Borders4x2', '0002_index_side2'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='border4x2',
            index=models.Index(fields=['side4'], name='Borders4x2__side4_f50554_idx'),
        ),
    ]
