# Generated by Django 4.2.7 on 2023-11-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Borders4x2', '0003_index_side4'),
    ]

    operations = [
        migrations.AddField(
            model_name='border4x2',
            name='side3',
            field=models.CharField(default='', max_length=4),
        ),
    ]

# end of file
