# Generated by Django 4.2.7 on 2023-11-09 21:05

from django.db import migrations, models


def get_side(piece, side_nr: int, rot: int) -> str:
    """
        rot = number of counterclockwise rotations (0..3)

        rot  side_nr=1  2  3  4
        ---          ----------
         0           1  2  3  4
         1           2  3  4  1
         2           3  4  1  2
         3           4  1  2  3

        rot+side_nr  return
         1           side1
         2           side2
         3           side3
         4           side4
         5           side1
         6           side2
         7           side3
    """
    side_nr += rot
    if side_nr in (1, 5):
        side = piece.side1
    elif side_nr in (2, 6):
        side = piece.side2
    elif side_nr in (3, 7):
        side = piece.side3
    else:
        side = piece.side4
    return side[0:1]


def calc_side3(apps, _):

    base_klas = apps.get_model('BasePieces', 'BasePiece')
    border_klas = apps.get_model('Borders4x2', 'Border4x2')

    nr2base = dict()    # [nr] = BasePiece
    for piece in base_klas.objects.all():
        nr2base[piece.nr] = piece
    # for

    """
                  side1 = border
                +---+---+---+---+
                | 1 | 2 | 3 | 4 |
         side 4 +---+---+---+---+ side 2
                | 5 | 6 | 7 | 8 |
                +---+---+---+---+
                      side 3
    """

    count = 0
    bulk = list()
    for border in border_klas.objects.all().iterator(chunk_size=100000):

        p5 = nr2base[border.nr5]
        s5 = get_side(p5, 3, border.rot5)

        p6 = nr2base[border.nr5]
        s6 = get_side(p6, 3, border.rot6)

        p7 = nr2base[border.nr5]
        s7 = get_side(p7, 3, border.rot7)

        p8 = nr2base[border.nr5]
        s8 = get_side(p8, 3, border.rot8)

        border.side3 = s8 + s7 + s6 + s5

        bulk.append(border)

        if len(bulk) == 100000:
            count += len(bulk)
            print(count)
            border_klas.objects.bulk_update(bulk, ['side3'])
            bulk = list()
    # for


class Migration(migrations.Migration):

    dependencies = [
        ('Borders4x2', '0003_index_side4'),
    ]

    operations = [
        migrations.AddField(
            model_name='border4x2',
            name='side3',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.RunPython(calc_side3, reverse_code=migrations.RunPython.noop)
    ]

# end of file
