# Generated by Django 4.2.7 on 2023-11-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorderSolution',
            fields=[
                ('nr', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('c1', models.PositiveIntegerField()),
                ('c2', models.PositiveIntegerField()),
                ('c3', models.PositiveIntegerField()),
                ('c4', models.PositiveIntegerField()),
                ('b1', models.PositiveIntegerField()),
                ('b2', models.PositiveIntegerField()),
                ('b3', models.PositiveIntegerField()),
                ('b4', models.PositiveIntegerField()),
                ('b5', models.PositiveIntegerField()),
                ('b6', models.PositiveIntegerField()),
                ('b7', models.PositiveIntegerField()),
                ('b8', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Border solution',
            },
        ),
    ]

# end of file
