# Generated by Django 4.2.7 on 2023-12-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pieces3x3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='piece3x3',
            name='Pieces3x3_p_is_bord_802d89_idx',
        ),
        migrations.RemoveField(
            model_name='piece3x3',
            name='is_border',
        ),
    ]
