# Generated by Django 4.2.7 on 2023-12-27 08:05

from django.db import migrations, models


def init_next(apps, _):
    klas = apps.get_model('Pieces3x3', 'Make3x3Next')

    # create the one and only instance
    klas().save()


class Migration(migrations.Migration):

    dependencies = [
        ('Pieces3x3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make3x3Next',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_p1', models.PositiveSmallIntegerField(default=61)),
            ],
        ),

        migrations.RunPython(init_next),
    ]


# end of file
