# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: E2 Solver 2023
description: >- # this means to ignore newlines until "baseurl:"
  Solver for the Eternity II puzzle using novel algorithms and web development technology
author: Ramon van der Winkel
github_username:  RamonvdW

# contents of baseurl gets added in by relative_url
baseurl: "/e2solver23"     # the subpath of your site, e.g. /blog

url: ""         # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima

#plugins:
#  - jekyll-feed
# we don't want the feed, ever.
# by setting this flag it is left out.
feed:
 disable_in_development: true

# stop complaining about minima
sass:
  quiet_deps: true

destination: ../docs/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
- HOWTO.txt

#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
